/* soapArgumentSettingServiceSoapProxy.h
   Generated by gSOAP 2.8.84 for .\SunacCADService2.h

gSOAP XML Web services tools
Copyright (C) 2000-2018, Robert van Engelen, Genivia Inc. All Rights Reserved.
The soapcpp2 tool and its generated software are released under the GPL.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
A commercial use license is available from Genivia Inc., contact@genivia.com
--------------------------------------------------------------------------------
*/

#ifndef soapArgumentSettingServiceSoapProxy_H
#define soapArgumentSettingServiceSoapProxy_H
#include "soapH.h"

    class SOAP_CMAC ArgumentSettingServiceSoapProxy : public soap {
      public:
        /// Endpoint URL of service 'ArgumentSettingServiceSoapProxy' (change as needed)
        const char *soap_endpoint;
        /// Variables globally declared in .\SunacCADService2.h, if any
        /// Construct a proxy with new managing context
        ArgumentSettingServiceSoapProxy();
        /// Copy constructor
        ArgumentSettingServiceSoapProxy(const ArgumentSettingServiceSoapProxy& rhs);
        /// Construct proxy given a managing context
        ArgumentSettingServiceSoapProxy(const struct soap&);
        /// Construct proxy given a managing context and endpoint URL
        ArgumentSettingServiceSoapProxy(const struct soap&, const char *soap_endpoint_url);
        /// Constructor taking an endpoint URL
        ArgumentSettingServiceSoapProxy(const char *soap_endpoint_url);
        /// Constructor taking input and output mode flags for the new managing context
        ArgumentSettingServiceSoapProxy(soap_mode iomode);
        /// Constructor taking endpoint URL and input and output mode flags for the new managing context
        ArgumentSettingServiceSoapProxy(const char *soap_endpoint_url, soap_mode iomode);
        /// Constructor taking input and output mode flags for the new managing context
        ArgumentSettingServiceSoapProxy(soap_mode imode, soap_mode omode);
        /// Destructor deletes deserialized data and its managing context
        virtual ~ArgumentSettingServiceSoapProxy();
        /// Initializer used by constructors
        virtual void ArgumentSettingServiceSoapProxy_init(soap_mode imode, soap_mode omode);
        /// Return a copy that has a new managing context with the same engine state
        virtual ArgumentSettingServiceSoapProxy *copy();
        /// Copy assignment
        ArgumentSettingServiceSoapProxy& operator=(const ArgumentSettingServiceSoapProxy&);
        /// Delete all deserialized data (uses soap_destroy() and soap_end())
        virtual void destroy();
        /// Delete all deserialized data and reset to default
        virtual void reset();
        /// Disables and removes SOAP Header from message by setting soap->header = NULL
        virtual void soap_noheader();
        /// Get SOAP Header structure (i.e. soap->header, which is NULL when absent)
        virtual ::SOAP_ENV__Header *soap_header();
        /// Get SOAP Fault structure (i.e. soap->fault, which is NULL when absent)
        virtual ::SOAP_ENV__Fault *soap_fault();
        /// Get SOAP Fault subcode QName string (NULL when absent)
        virtual const char *soap_fault_subcode();
        /// Get SOAP Fault string/reason (NULL when absent)
        virtual const char *soap_fault_string();
        /// Get SOAP Fault detail XML string (NULL when absent)
        virtual const char *soap_fault_detail();
        /// Close connection (normally automatic, except for send_X ops)
        virtual int soap_close_socket();
        /// Force close connection (can kill a thread blocked on IO)
        virtual int soap_force_close_socket();
        /// Print fault
        virtual void soap_print_fault(FILE*);
    #ifndef WITH_LEAN
    #ifndef WITH_COMPAT
        /// Print fault to stream
        virtual void soap_stream_fault(std::ostream&);
    #endif
        /// Write fault to buffer
        virtual char *soap_sprint_fault(char *buf, size_t len);
    #endif
        //
        /// Web service synchronous operation 'StandardDesignAttribute' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int StandardDesignAttribute(_ns1__StandardDesignAttribute *ns1__StandardDesignAttribute, _ns1__StandardDesignAttributeResponse &ns1__StandardDesignAttributeResponse) { return this->StandardDesignAttribute(NULL, NULL, ns1__StandardDesignAttribute, ns1__StandardDesignAttributeResponse); }
        /// Web service synchronous operation 'StandardDesignAttribute' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int StandardDesignAttribute(const char *soap_endpoint_url, const char *soap_action, _ns1__StandardDesignAttribute *ns1__StandardDesignAttribute, _ns1__StandardDesignAttributeResponse &ns1__StandardDesignAttributeResponse) { return this->send_StandardDesignAttribute(soap_endpoint_url, soap_action, ns1__StandardDesignAttribute) || this->recv_StandardDesignAttribute(ns1__StandardDesignAttributeResponse) ? this->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_StandardDesignAttribute' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_StandardDesignAttribute(const char *soap_endpoint_url, const char *soap_action, _ns1__StandardDesignAttribute *ns1__StandardDesignAttribute);
        /// Web service asynchronous operation 'recv_StandardDesignAttribute' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_StandardDesignAttribute(_ns1__StandardDesignAttributeResponse &ns1__StandardDesignAttributeResponse);
        //
        /// Web service synchronous operation 'GetAllWindows' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int GetAllWindows(_ns1__GetAllWindows *ns1__GetAllWindows, _ns1__GetAllWindowsResponse &ns1__GetAllWindowsResponse) { return this->GetAllWindows(NULL, NULL, ns1__GetAllWindows, ns1__GetAllWindowsResponse); }
        /// Web service synchronous operation 'GetAllWindows' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int GetAllWindows(const char *soap_endpoint_url, const char *soap_action, _ns1__GetAllWindows *ns1__GetAllWindows, _ns1__GetAllWindowsResponse &ns1__GetAllWindowsResponse) { return this->send_GetAllWindows(soap_endpoint_url, soap_action, ns1__GetAllWindows) || this->recv_GetAllWindows(ns1__GetAllWindowsResponse) ? this->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_GetAllWindows' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_GetAllWindows(const char *soap_endpoint_url, const char *soap_action, _ns1__GetAllWindows *ns1__GetAllWindows);
        /// Web service asynchronous operation 'recv_GetAllWindows' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_GetAllWindows(_ns1__GetAllWindowsResponse &ns1__GetAllWindowsResponse);
        //
        /// Web service synchronous operation 'GetWindows' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int GetWindows(_ns1__GetWindows *ns1__GetWindows, _ns1__GetWindowsResponse &ns1__GetWindowsResponse) { return this->GetWindows(NULL, NULL, ns1__GetWindows, ns1__GetWindowsResponse); }
        /// Web service synchronous operation 'GetWindows' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int GetWindows(const char *soap_endpoint_url, const char *soap_action, _ns1__GetWindows *ns1__GetWindows, _ns1__GetWindowsResponse &ns1__GetWindowsResponse) { return this->send_GetWindows(soap_endpoint_url, soap_action, ns1__GetWindows) || this->recv_GetWindows(ns1__GetWindowsResponse) ? this->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_GetWindows' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_GetWindows(const char *soap_endpoint_url, const char *soap_action, _ns1__GetWindows *ns1__GetWindows);
        /// Web service asynchronous operation 'recv_GetWindows' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_GetWindows(_ns1__GetWindowsResponse &ns1__GetWindowsResponse);
        //
        /// Web service synchronous operation 'GetAllDoor' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int GetAllDoor(_ns1__GetAllDoor *ns1__GetAllDoor, _ns1__GetAllDoorResponse &ns1__GetAllDoorResponse) { return this->GetAllDoor(NULL, NULL, ns1__GetAllDoor, ns1__GetAllDoorResponse); }
        /// Web service synchronous operation 'GetAllDoor' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int GetAllDoor(const char *soap_endpoint_url, const char *soap_action, _ns1__GetAllDoor *ns1__GetAllDoor, _ns1__GetAllDoorResponse &ns1__GetAllDoorResponse) { return this->send_GetAllDoor(soap_endpoint_url, soap_action, ns1__GetAllDoor) || this->recv_GetAllDoor(ns1__GetAllDoorResponse) ? this->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_GetAllDoor' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_GetAllDoor(const char *soap_endpoint_url, const char *soap_action, _ns1__GetAllDoor *ns1__GetAllDoor);
        /// Web service asynchronous operation 'recv_GetAllDoor' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_GetAllDoor(_ns1__GetAllDoorResponse &ns1__GetAllDoorResponse);
        //
        /// Web service synchronous operation 'GetAllDoorByParam' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int GetAllDoorByParam(_ns1__GetAllDoorByParam *ns1__GetAllDoorByParam, _ns1__GetAllDoorByParamResponse &ns1__GetAllDoorByParamResponse) { return this->GetAllDoorByParam(NULL, NULL, ns1__GetAllDoorByParam, ns1__GetAllDoorByParamResponse); }
        /// Web service synchronous operation 'GetAllDoorByParam' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int GetAllDoorByParam(const char *soap_endpoint_url, const char *soap_action, _ns1__GetAllDoorByParam *ns1__GetAllDoorByParam, _ns1__GetAllDoorByParamResponse &ns1__GetAllDoorByParamResponse) { return this->send_GetAllDoorByParam(soap_endpoint_url, soap_action, ns1__GetAllDoorByParam) || this->recv_GetAllDoorByParam(ns1__GetAllDoorByParamResponse) ? this->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_GetAllDoorByParam' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_GetAllDoorByParam(const char *soap_endpoint_url, const char *soap_action, _ns1__GetAllDoorByParam *ns1__GetAllDoorByParam);
        /// Web service asynchronous operation 'recv_GetAllDoorByParam' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_GetAllDoorByParam(_ns1__GetAllDoorByParamResponse &ns1__GetAllDoorByParamResponse);
        //
        /// Web service synchronous operation 'GetAllKitchen' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int GetAllKitchen(_ns1__GetAllKitchen *ns1__GetAllKitchen, _ns1__GetAllKitchenResponse &ns1__GetAllKitchenResponse) { return this->GetAllKitchen(NULL, NULL, ns1__GetAllKitchen, ns1__GetAllKitchenResponse); }
        /// Web service synchronous operation 'GetAllKitchen' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int GetAllKitchen(const char *soap_endpoint_url, const char *soap_action, _ns1__GetAllKitchen *ns1__GetAllKitchen, _ns1__GetAllKitchenResponse &ns1__GetAllKitchenResponse) { return this->send_GetAllKitchen(soap_endpoint_url, soap_action, ns1__GetAllKitchen) || this->recv_GetAllKitchen(ns1__GetAllKitchenResponse) ? this->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_GetAllKitchen' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_GetAllKitchen(const char *soap_endpoint_url, const char *soap_action, _ns1__GetAllKitchen *ns1__GetAllKitchen);
        /// Web service asynchronous operation 'recv_GetAllKitchen' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_GetAllKitchen(_ns1__GetAllKitchenResponse &ns1__GetAllKitchenResponse);
        //
        /// Web service synchronous operation 'GetAllKitchenParam' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int GetAllKitchenParam(_ns1__GetAllKitchenParam *ns1__GetAllKitchenParam, _ns1__GetAllKitchenParamResponse &ns1__GetAllKitchenParamResponse) { return this->GetAllKitchenParam(NULL, NULL, ns1__GetAllKitchenParam, ns1__GetAllKitchenParamResponse); }
        /// Web service synchronous operation 'GetAllKitchenParam' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int GetAllKitchenParam(const char *soap_endpoint_url, const char *soap_action, _ns1__GetAllKitchenParam *ns1__GetAllKitchenParam, _ns1__GetAllKitchenParamResponse &ns1__GetAllKitchenParamResponse) { return this->send_GetAllKitchenParam(soap_endpoint_url, soap_action, ns1__GetAllKitchenParam) || this->recv_GetAllKitchenParam(ns1__GetAllKitchenParamResponse) ? this->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_GetAllKitchenParam' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_GetAllKitchenParam(const char *soap_endpoint_url, const char *soap_action, _ns1__GetAllKitchenParam *ns1__GetAllKitchenParam);
        /// Web service asynchronous operation 'recv_GetAllKitchenParam' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_GetAllKitchenParam(_ns1__GetAllKitchenParamResponse &ns1__GetAllKitchenParamResponse);
        //
        /// Web service synchronous operation 'GetAllBathroom' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int GetAllBathroom(_ns1__GetAllBathroom *ns1__GetAllBathroom, _ns1__GetAllBathroomResponse &ns1__GetAllBathroomResponse) { return this->GetAllBathroom(NULL, NULL, ns1__GetAllBathroom, ns1__GetAllBathroomResponse); }
        /// Web service synchronous operation 'GetAllBathroom' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int GetAllBathroom(const char *soap_endpoint_url, const char *soap_action, _ns1__GetAllBathroom *ns1__GetAllBathroom, _ns1__GetAllBathroomResponse &ns1__GetAllBathroomResponse) { return this->send_GetAllBathroom(soap_endpoint_url, soap_action, ns1__GetAllBathroom) || this->recv_GetAllBathroom(ns1__GetAllBathroomResponse) ? this->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_GetAllBathroom' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_GetAllBathroom(const char *soap_endpoint_url, const char *soap_action, _ns1__GetAllBathroom *ns1__GetAllBathroom);
        /// Web service asynchronous operation 'recv_GetAllBathroom' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_GetAllBathroom(_ns1__GetAllBathroomResponse &ns1__GetAllBathroomResponse);
        //
        /// Web service synchronous operation 'GetAllBathroomByParam' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int GetAllBathroomByParam(_ns1__GetAllBathroomByParam *ns1__GetAllBathroomByParam, _ns1__GetAllBathroomByParamResponse &ns1__GetAllBathroomByParamResponse) { return this->GetAllBathroomByParam(NULL, NULL, ns1__GetAllBathroomByParam, ns1__GetAllBathroomByParamResponse); }
        /// Web service synchronous operation 'GetAllBathroomByParam' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int GetAllBathroomByParam(const char *soap_endpoint_url, const char *soap_action, _ns1__GetAllBathroomByParam *ns1__GetAllBathroomByParam, _ns1__GetAllBathroomByParamResponse &ns1__GetAllBathroomByParamResponse) { return this->send_GetAllBathroomByParam(soap_endpoint_url, soap_action, ns1__GetAllBathroomByParam) || this->recv_GetAllBathroomByParam(ns1__GetAllBathroomByParamResponse) ? this->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_GetAllBathroomByParam' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_GetAllBathroomByParam(const char *soap_endpoint_url, const char *soap_action, _ns1__GetAllBathroomByParam *ns1__GetAllBathroomByParam);
        /// Web service asynchronous operation 'recv_GetAllBathroomByParam' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_GetAllBathroomByParam(_ns1__GetAllBathroomByParamResponse &ns1__GetAllBathroomByParamResponse);
        //
        /// Web service synchronous operation 'GetAllHandrailByParam' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int GetAllHandrailByParam(_ns1__GetAllHandrailByParam *ns1__GetAllHandrailByParam, _ns1__GetAllHandrailByParamResponse &ns1__GetAllHandrailByParamResponse) { return this->GetAllHandrailByParam(NULL, NULL, ns1__GetAllHandrailByParam, ns1__GetAllHandrailByParamResponse); }
        /// Web service synchronous operation 'GetAllHandrailByParam' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int GetAllHandrailByParam(const char *soap_endpoint_url, const char *soap_action, _ns1__GetAllHandrailByParam *ns1__GetAllHandrailByParam, _ns1__GetAllHandrailByParamResponse &ns1__GetAllHandrailByParamResponse) { return this->send_GetAllHandrailByParam(soap_endpoint_url, soap_action, ns1__GetAllHandrailByParam) || this->recv_GetAllHandrailByParam(ns1__GetAllHandrailByParamResponse) ? this->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_GetAllHandrailByParam' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_GetAllHandrailByParam(const char *soap_endpoint_url, const char *soap_action, _ns1__GetAllHandrailByParam *ns1__GetAllHandrailByParam);
        /// Web service asynchronous operation 'recv_GetAllHandrailByParam' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_GetAllHandrailByParam(_ns1__GetAllHandrailByParamResponse &ns1__GetAllHandrailByParamResponse);
        //
        /// Web service synchronous operation 'GetAllAirconditionerByParam' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int GetAllAirconditionerByParam(_ns1__GetAllAirconditionerByParam *ns1__GetAllAirconditionerByParam, _ns1__GetAllAirconditionerByParamResponse &ns1__GetAllAirconditionerByParamResponse) { return this->GetAllAirconditionerByParam(NULL, NULL, ns1__GetAllAirconditionerByParam, ns1__GetAllAirconditionerByParamResponse); }
        /// Web service synchronous operation 'GetAllAirconditionerByParam' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int GetAllAirconditionerByParam(const char *soap_endpoint_url, const char *soap_action, _ns1__GetAllAirconditionerByParam *ns1__GetAllAirconditionerByParam, _ns1__GetAllAirconditionerByParamResponse &ns1__GetAllAirconditionerByParamResponse) { return this->send_GetAllAirconditionerByParam(soap_endpoint_url, soap_action, ns1__GetAllAirconditionerByParam) || this->recv_GetAllAirconditionerByParam(ns1__GetAllAirconditionerByParamResponse) ? this->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_GetAllAirconditionerByParam' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_GetAllAirconditionerByParam(const char *soap_endpoint_url, const char *soap_action, _ns1__GetAllAirconditionerByParam *ns1__GetAllAirconditionerByParam);
        /// Web service asynchronous operation 'recv_GetAllAirconditionerByParam' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_GetAllAirconditionerByParam(_ns1__GetAllAirconditionerByParamResponse &ns1__GetAllAirconditionerByParamResponse);
        //
        /// Web service synchronous operation 'CadFileDownload' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int CadFileDownload(_ns1__CadFileDownload *ns1__CadFileDownload, _ns1__CadFileDownloadResponse &ns1__CadFileDownloadResponse) { return this->CadFileDownload(NULL, NULL, ns1__CadFileDownload, ns1__CadFileDownloadResponse); }
        /// Web service synchronous operation 'CadFileDownload' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int CadFileDownload(const char *soap_endpoint_url, const char *soap_action, _ns1__CadFileDownload *ns1__CadFileDownload, _ns1__CadFileDownloadResponse &ns1__CadFileDownloadResponse) { return this->send_CadFileDownload(soap_endpoint_url, soap_action, ns1__CadFileDownload) || this->recv_CadFileDownload(ns1__CadFileDownloadResponse) ? this->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_CadFileDownload' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_CadFileDownload(const char *soap_endpoint_url, const char *soap_action, _ns1__CadFileDownload *ns1__CadFileDownload);
        /// Web service asynchronous operation 'recv_CadFileDownload' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_CadFileDownload(_ns1__CadFileDownloadResponse &ns1__CadFileDownloadResponse);
        //
        /// Web service synchronous operation 'StandardDesignAttribute' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int StandardDesignAttribute_(_ns1__StandardDesignAttribute *ns1__StandardDesignAttribute, _ns1__StandardDesignAttributeResponse &ns1__StandardDesignAttributeResponse) { return this->StandardDesignAttribute_(NULL, NULL, ns1__StandardDesignAttribute, ns1__StandardDesignAttributeResponse); }
        /// Web service synchronous operation 'StandardDesignAttribute' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int StandardDesignAttribute_(const char *soap_endpoint_url, const char *soap_action, _ns1__StandardDesignAttribute *ns1__StandardDesignAttribute, _ns1__StandardDesignAttributeResponse &ns1__StandardDesignAttributeResponse) { return this->send_StandardDesignAttribute_(soap_endpoint_url, soap_action, ns1__StandardDesignAttribute) || this->recv_StandardDesignAttribute_(ns1__StandardDesignAttributeResponse) ? this->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_StandardDesignAttribute' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_StandardDesignAttribute_(const char *soap_endpoint_url, const char *soap_action, _ns1__StandardDesignAttribute *ns1__StandardDesignAttribute);
        /// Web service asynchronous operation 'recv_StandardDesignAttribute' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_StandardDesignAttribute_(_ns1__StandardDesignAttributeResponse &ns1__StandardDesignAttributeResponse);
        //
        /// Web service synchronous operation 'GetAllWindows' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int GetAllWindows_(_ns1__GetAllWindows *ns1__GetAllWindows, _ns1__GetAllWindowsResponse &ns1__GetAllWindowsResponse) { return this->GetAllWindows_(NULL, NULL, ns1__GetAllWindows, ns1__GetAllWindowsResponse); }
        /// Web service synchronous operation 'GetAllWindows' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int GetAllWindows_(const char *soap_endpoint_url, const char *soap_action, _ns1__GetAllWindows *ns1__GetAllWindows, _ns1__GetAllWindowsResponse &ns1__GetAllWindowsResponse) { return this->send_GetAllWindows_(soap_endpoint_url, soap_action, ns1__GetAllWindows) || this->recv_GetAllWindows_(ns1__GetAllWindowsResponse) ? this->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_GetAllWindows' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_GetAllWindows_(const char *soap_endpoint_url, const char *soap_action, _ns1__GetAllWindows *ns1__GetAllWindows);
        /// Web service asynchronous operation 'recv_GetAllWindows' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_GetAllWindows_(_ns1__GetAllWindowsResponse &ns1__GetAllWindowsResponse);
        //
        /// Web service synchronous operation 'GetWindows' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int GetWindows_(_ns1__GetWindows *ns1__GetWindows, _ns1__GetWindowsResponse &ns1__GetWindowsResponse) { return this->GetWindows_(NULL, NULL, ns1__GetWindows, ns1__GetWindowsResponse); }
        /// Web service synchronous operation 'GetWindows' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int GetWindows_(const char *soap_endpoint_url, const char *soap_action, _ns1__GetWindows *ns1__GetWindows, _ns1__GetWindowsResponse &ns1__GetWindowsResponse) { return this->send_GetWindows_(soap_endpoint_url, soap_action, ns1__GetWindows) || this->recv_GetWindows_(ns1__GetWindowsResponse) ? this->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_GetWindows' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_GetWindows_(const char *soap_endpoint_url, const char *soap_action, _ns1__GetWindows *ns1__GetWindows);
        /// Web service asynchronous operation 'recv_GetWindows' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_GetWindows_(_ns1__GetWindowsResponse &ns1__GetWindowsResponse);
        //
        /// Web service synchronous operation 'GetAllDoor' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int GetAllDoor_(_ns1__GetAllDoor *ns1__GetAllDoor, _ns1__GetAllDoorResponse &ns1__GetAllDoorResponse) { return this->GetAllDoor_(NULL, NULL, ns1__GetAllDoor, ns1__GetAllDoorResponse); }
        /// Web service synchronous operation 'GetAllDoor' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int GetAllDoor_(const char *soap_endpoint_url, const char *soap_action, _ns1__GetAllDoor *ns1__GetAllDoor, _ns1__GetAllDoorResponse &ns1__GetAllDoorResponse) { return this->send_GetAllDoor_(soap_endpoint_url, soap_action, ns1__GetAllDoor) || this->recv_GetAllDoor_(ns1__GetAllDoorResponse) ? this->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_GetAllDoor' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_GetAllDoor_(const char *soap_endpoint_url, const char *soap_action, _ns1__GetAllDoor *ns1__GetAllDoor);
        /// Web service asynchronous operation 'recv_GetAllDoor' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_GetAllDoor_(_ns1__GetAllDoorResponse &ns1__GetAllDoorResponse);
        //
        /// Web service synchronous operation 'GetAllDoorByParam' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int GetAllDoorByParam_(_ns1__GetAllDoorByParam *ns1__GetAllDoorByParam, _ns1__GetAllDoorByParamResponse &ns1__GetAllDoorByParamResponse) { return this->GetAllDoorByParam_(NULL, NULL, ns1__GetAllDoorByParam, ns1__GetAllDoorByParamResponse); }
        /// Web service synchronous operation 'GetAllDoorByParam' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int GetAllDoorByParam_(const char *soap_endpoint_url, const char *soap_action, _ns1__GetAllDoorByParam *ns1__GetAllDoorByParam, _ns1__GetAllDoorByParamResponse &ns1__GetAllDoorByParamResponse) { return this->send_GetAllDoorByParam_(soap_endpoint_url, soap_action, ns1__GetAllDoorByParam) || this->recv_GetAllDoorByParam_(ns1__GetAllDoorByParamResponse) ? this->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_GetAllDoorByParam' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_GetAllDoorByParam_(const char *soap_endpoint_url, const char *soap_action, _ns1__GetAllDoorByParam *ns1__GetAllDoorByParam);
        /// Web service asynchronous operation 'recv_GetAllDoorByParam' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_GetAllDoorByParam_(_ns1__GetAllDoorByParamResponse &ns1__GetAllDoorByParamResponse);
        //
        /// Web service synchronous operation 'GetAllKitchen' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int GetAllKitchen_(_ns1__GetAllKitchen *ns1__GetAllKitchen, _ns1__GetAllKitchenResponse &ns1__GetAllKitchenResponse) { return this->GetAllKitchen_(NULL, NULL, ns1__GetAllKitchen, ns1__GetAllKitchenResponse); }
        /// Web service synchronous operation 'GetAllKitchen' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int GetAllKitchen_(const char *soap_endpoint_url, const char *soap_action, _ns1__GetAllKitchen *ns1__GetAllKitchen, _ns1__GetAllKitchenResponse &ns1__GetAllKitchenResponse) { return this->send_GetAllKitchen_(soap_endpoint_url, soap_action, ns1__GetAllKitchen) || this->recv_GetAllKitchen_(ns1__GetAllKitchenResponse) ? this->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_GetAllKitchen' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_GetAllKitchen_(const char *soap_endpoint_url, const char *soap_action, _ns1__GetAllKitchen *ns1__GetAllKitchen);
        /// Web service asynchronous operation 'recv_GetAllKitchen' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_GetAllKitchen_(_ns1__GetAllKitchenResponse &ns1__GetAllKitchenResponse);
        //
        /// Web service synchronous operation 'GetAllKitchenParam' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int GetAllKitchenParam_(_ns1__GetAllKitchenParam *ns1__GetAllKitchenParam, _ns1__GetAllKitchenParamResponse &ns1__GetAllKitchenParamResponse) { return this->GetAllKitchenParam_(NULL, NULL, ns1__GetAllKitchenParam, ns1__GetAllKitchenParamResponse); }
        /// Web service synchronous operation 'GetAllKitchenParam' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int GetAllKitchenParam_(const char *soap_endpoint_url, const char *soap_action, _ns1__GetAllKitchenParam *ns1__GetAllKitchenParam, _ns1__GetAllKitchenParamResponse &ns1__GetAllKitchenParamResponse) { return this->send_GetAllKitchenParam_(soap_endpoint_url, soap_action, ns1__GetAllKitchenParam) || this->recv_GetAllKitchenParam_(ns1__GetAllKitchenParamResponse) ? this->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_GetAllKitchenParam' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_GetAllKitchenParam_(const char *soap_endpoint_url, const char *soap_action, _ns1__GetAllKitchenParam *ns1__GetAllKitchenParam);
        /// Web service asynchronous operation 'recv_GetAllKitchenParam' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_GetAllKitchenParam_(_ns1__GetAllKitchenParamResponse &ns1__GetAllKitchenParamResponse);
        //
        /// Web service synchronous operation 'GetAllBathroom' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int GetAllBathroom_(_ns1__GetAllBathroom *ns1__GetAllBathroom, _ns1__GetAllBathroomResponse &ns1__GetAllBathroomResponse) { return this->GetAllBathroom_(NULL, NULL, ns1__GetAllBathroom, ns1__GetAllBathroomResponse); }
        /// Web service synchronous operation 'GetAllBathroom' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int GetAllBathroom_(const char *soap_endpoint_url, const char *soap_action, _ns1__GetAllBathroom *ns1__GetAllBathroom, _ns1__GetAllBathroomResponse &ns1__GetAllBathroomResponse) { return this->send_GetAllBathroom_(soap_endpoint_url, soap_action, ns1__GetAllBathroom) || this->recv_GetAllBathroom_(ns1__GetAllBathroomResponse) ? this->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_GetAllBathroom' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_GetAllBathroom_(const char *soap_endpoint_url, const char *soap_action, _ns1__GetAllBathroom *ns1__GetAllBathroom);
        /// Web service asynchronous operation 'recv_GetAllBathroom' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_GetAllBathroom_(_ns1__GetAllBathroomResponse &ns1__GetAllBathroomResponse);
        //
        /// Web service synchronous operation 'GetAllBathroomByParam' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int GetAllBathroomByParam_(_ns1__GetAllBathroomByParam *ns1__GetAllBathroomByParam, _ns1__GetAllBathroomByParamResponse &ns1__GetAllBathroomByParamResponse) { return this->GetAllBathroomByParam_(NULL, NULL, ns1__GetAllBathroomByParam, ns1__GetAllBathroomByParamResponse); }
        /// Web service synchronous operation 'GetAllBathroomByParam' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int GetAllBathroomByParam_(const char *soap_endpoint_url, const char *soap_action, _ns1__GetAllBathroomByParam *ns1__GetAllBathroomByParam, _ns1__GetAllBathroomByParamResponse &ns1__GetAllBathroomByParamResponse) { return this->send_GetAllBathroomByParam_(soap_endpoint_url, soap_action, ns1__GetAllBathroomByParam) || this->recv_GetAllBathroomByParam_(ns1__GetAllBathroomByParamResponse) ? this->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_GetAllBathroomByParam' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_GetAllBathroomByParam_(const char *soap_endpoint_url, const char *soap_action, _ns1__GetAllBathroomByParam *ns1__GetAllBathroomByParam);
        /// Web service asynchronous operation 'recv_GetAllBathroomByParam' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_GetAllBathroomByParam_(_ns1__GetAllBathroomByParamResponse &ns1__GetAllBathroomByParamResponse);
        //
        /// Web service synchronous operation 'GetAllHandrailByParam' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int GetAllHandrailByParam_(_ns1__GetAllHandrailByParam *ns1__GetAllHandrailByParam, _ns1__GetAllHandrailByParamResponse &ns1__GetAllHandrailByParamResponse) { return this->GetAllHandrailByParam_(NULL, NULL, ns1__GetAllHandrailByParam, ns1__GetAllHandrailByParamResponse); }
        /// Web service synchronous operation 'GetAllHandrailByParam' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int GetAllHandrailByParam_(const char *soap_endpoint_url, const char *soap_action, _ns1__GetAllHandrailByParam *ns1__GetAllHandrailByParam, _ns1__GetAllHandrailByParamResponse &ns1__GetAllHandrailByParamResponse) { return this->send_GetAllHandrailByParam_(soap_endpoint_url, soap_action, ns1__GetAllHandrailByParam) || this->recv_GetAllHandrailByParam_(ns1__GetAllHandrailByParamResponse) ? this->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_GetAllHandrailByParam' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_GetAllHandrailByParam_(const char *soap_endpoint_url, const char *soap_action, _ns1__GetAllHandrailByParam *ns1__GetAllHandrailByParam);
        /// Web service asynchronous operation 'recv_GetAllHandrailByParam' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_GetAllHandrailByParam_(_ns1__GetAllHandrailByParamResponse &ns1__GetAllHandrailByParamResponse);
        //
        /// Web service synchronous operation 'GetAllAirconditionerByParam' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int GetAllAirconditionerByParam_(_ns1__GetAllAirconditionerByParam *ns1__GetAllAirconditionerByParam, _ns1__GetAllAirconditionerByParamResponse &ns1__GetAllAirconditionerByParamResponse) { return this->GetAllAirconditionerByParam_(NULL, NULL, ns1__GetAllAirconditionerByParam, ns1__GetAllAirconditionerByParamResponse); }
        /// Web service synchronous operation 'GetAllAirconditionerByParam' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int GetAllAirconditionerByParam_(const char *soap_endpoint_url, const char *soap_action, _ns1__GetAllAirconditionerByParam *ns1__GetAllAirconditionerByParam, _ns1__GetAllAirconditionerByParamResponse &ns1__GetAllAirconditionerByParamResponse) { return this->send_GetAllAirconditionerByParam_(soap_endpoint_url, soap_action, ns1__GetAllAirconditionerByParam) || this->recv_GetAllAirconditionerByParam_(ns1__GetAllAirconditionerByParamResponse) ? this->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_GetAllAirconditionerByParam' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_GetAllAirconditionerByParam_(const char *soap_endpoint_url, const char *soap_action, _ns1__GetAllAirconditionerByParam *ns1__GetAllAirconditionerByParam);
        /// Web service asynchronous operation 'recv_GetAllAirconditionerByParam' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_GetAllAirconditionerByParam_(_ns1__GetAllAirconditionerByParamResponse &ns1__GetAllAirconditionerByParamResponse);
        //
        /// Web service synchronous operation 'CadFileDownload' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int CadFileDownload_(_ns1__CadFileDownload *ns1__CadFileDownload, _ns1__CadFileDownloadResponse &ns1__CadFileDownloadResponse) { return this->CadFileDownload_(NULL, NULL, ns1__CadFileDownload, ns1__CadFileDownloadResponse); }
        /// Web service synchronous operation 'CadFileDownload' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int CadFileDownload_(const char *soap_endpoint_url, const char *soap_action, _ns1__CadFileDownload *ns1__CadFileDownload, _ns1__CadFileDownloadResponse &ns1__CadFileDownloadResponse) { return this->send_CadFileDownload_(soap_endpoint_url, soap_action, ns1__CadFileDownload) || this->recv_CadFileDownload_(ns1__CadFileDownloadResponse) ? this->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_CadFileDownload' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_CadFileDownload_(const char *soap_endpoint_url, const char *soap_action, _ns1__CadFileDownload *ns1__CadFileDownload);
        /// Web service asynchronous operation 'recv_CadFileDownload' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_CadFileDownload_(_ns1__CadFileDownloadResponse &ns1__CadFileDownloadResponse);
    };
#endif
